routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * Image resizer
 */
Route::get('/image/{h}/{w}/{img?}',function($w=200, $h=200, $img) {
	$image = Image::cache(function($image) use($img, $w, $h) {
	    $image->make(public_path("/$img"))->heighten($h);
	});
	return response($image, 200)->header('Content-Type', 'image/jpg');
})->name('image')->where('img', '(.*)');


/**
 * 1C exchange
 */
Route::middleware('auth.1c')->prefix('exchange')->group(function () {
    Route::any('', 'Exchange\ExchangeController@index');
    Route::post('promocodes', 'Exchange\PromocodeController@generate');
    Route::post('bonus-cards/create', 'Exchange\BonusCardController@create');
    Route::get('bonus-cards/{search}', 'Exchange\BonusCardController@show');
//    Route::post('bonus-cards/{search}', 'Exchange\BonusCardController@storeBonusLog');
    Route::get('orders/{id}', 'Exchange\OrderController@get');
    Route::post('orders/{order}/{status}', 'Exchange\OrderController@changeStatus');
});


/**
 * Auth
 */
Route::get('/logout', 'Auth\LoginController@logout')->name('logout.get');

Route::post('/login', 'Auth\LoginController@login');

Route::post('/register', 'Auth\RegisterController@create');

Route::post('/sms/send-code', 'SmsCodeController@sendCodeForExistingUser');

Route::post('/register/send-code', 'SmsCodeController@sendCodeForRegister');

Route::post('/forget/send-code', 'SmsCodeController@sendCodeForFoggotPassword');

Route::post('/forget/change', 'Auth\ResetPasswordController@forgetpassword');

Route::middleware('geoip')->group(function() {
    Route::get('sitemap.xml', 'SeoController@sitemap')->name('seo.sitemap');
    Route::get('robots.txt', 'SeoController@robots')->name('seo.robots');
	/**
	 * Catalog
	 */
	Route::group(['prefix' => 'catalog'], function () {
		Route::get('', 'CatalogController@index')->name('catalog.index');
		Route::get('{category}', 'CatalogController@category')->name('catalog.category');
		Route::get('{category}/{slug}', 'CatalogController@view')->name('catalog.view');
		Route::post('search', 'CatalogController@search')->name('catalog.search');
	});

	/**
	 * Contacts
	 */
	Route::group(['prefix' => 'contacts'], function () {
		Route::get('', 'DrugstoreController@contacts')->name('contacts');
		Route::post('/select', 'DrugstoreController@select')->name('contacts.city');
	});

	/**
	 * Main page
	 */
	Route::get('/', 'MainController@main')->name('main');
	Route::post('/choose-city', 'MainController@chooseCity')->name('choose.city');
	Route::post('/choose-drugstore', 'MainController@chooseDrugstore')->name('choose.drugstore');
	Route::get('/drugstores', 'MainController@drugstores')->name('drugstores');

	/**
	 * Pages
	 */
	Route::group(['prefix' => '/page'], function () {
	    Route::get('{slug}', 'PageController@view')->name('page.view');
	});

	/**
	 * Vacancies
	 */
	Route::group(['prefix' => '/vacancies'], function () {
		Route::get('', 'VacancyController@index')->name('vacancies.index');
	});
	/**
	 * Resume
	 */
	Route::resource('resume', 'ResumeController', ['only' => [
	    'store'
	]]);

	/**
	 * Feedback
	 */
	Route::group(['prefix' => 'feedback'], function () {
		Route::get('', 'FeedbackController@index')->name('feedback.index');
		Route::post('send', 'FeedbackController@send')->name('feedback.send');
	});
	/**
	 * drug request
	 */
    Route::post('drug-request', 'DrugRequestController@post')->name('drug-request.post');

	/**
	 * Promotions
	 */
	Route::group(['prefix' => '/promotions'], function () {
		Route::get('', 'CatalogController@promotions')->name('promotions.index');
//		Route::get('search', 'PromotionController@search')->name('promotions.search');
	});

	/**
	 * Drugs
	 */
	Route::group(['prefix' => '/drugs'], function () {
		Route::post('autocomplete', 'DrugController@autocomplete')->name('drugs.autocomplete');
		Route::get('search', 'CatalogController@searchDrugs')->name('drugs.search');
	    Route::get('for-select', 'DrugController@forSelect')->name('crud.drugs.for_select');
	    Route::get('recommended/{drug}', 'DrugController@getRecommendedDrugs')->name('drugs.recommended');
	});

	Route::middleware(['web', 'admin.auth'])->get('users/for-select', 'UserController@forSelect')->name('crud.users.for_select');

	/**
	 * Favorites
	 */
	Route::group(['prefix' => '/favorites'], function () {
		Route::get('', 'FavoriteController@index')->name('favorites.index');
		Route::post('add', 'FavoriteController@add')->name('favorites.add');
		Route::post('delete', 'FavoriteController@delete')->name('favorites.delete');
		Route::post('search', 'FavoriteController@search')->name('favorites.search');
	});

	/**
	 * Cart
	 */
	Route::group(['prefix' => '/cart'], function () {
		Route::get('', 'CartController@index')->name('cart');
		Route::delete('/clear', 'CartController@clear')->name('cart.clear');
		Route::delete('{drug_id}', 'CartController@delete')->name('cart.delete');
		Route::post('add', 'CartController@add')->name('cart.add');
		Route::get('get', 'CartController@get')->name('cart.get');
	});

	/**
	 * Order
	 */
	Route::group(['prefix' => '/orders'], function () {
	    Route::post('', 'Api\V1\OrderController@add')->name('order.add');
	    // Route::get('', 'OrderController@store')->name('order.add');
	});

	/**
	 * Articles
	 */
	Route::group(['prefix' => '/articles'], function () {
		Route::get('/', 'ArticleController@index')->name('article.index');
		Route::get('{category}', 'ArticleController@category')->name('article.category');
	    Route::get('{category}/{slug}', 'ArticleController@view')->name('article.view');
	});

	/**
	 * Profile
	 */
	Route::group(['prefix' => '/profile'], function () {
		Route::get('', 'ProfileController@index')->name('profile');
		Route::get('orders', 'ProfileController@orders')->name('profile.orders');
	    Route::get('getOrders', 'ProfileController@getOrders')->name('profile.orders.get');
	    Route::post('orders/{orderId}', 'Api\V1\OrderController@cancel')->name('profile.orders.cancel');
		Route::get('favorites', 'ProfileController@favorites')->name('profile.favorites');
		//Бонусная карта
		Route::get('bonus', 'ProfileController@bonus')->name('profile.bonus');
		Route::post('createcard', 'ProfileController@createcard')->name('profile.bonuscreate');
		//Смена пароля
		Route::get('password', 'ProfileController@password')->name('profile.password');
		Route::post('changepswd', 'ProfileController@changepswd')->name('profile.changepswd');
		//Изменение профиля
		Route::post('edit', 'ProfileController@edit')->name('profile.edit');
		//Изменение профиля
		Route::post('change-notification', 'ProfileController@changeNotification')->name('profile.change-notification');
	});
    Route::fallback(function () {
        return view('errors.404');
    });
});

app/Models/Drug.php
<?php

namespace App\Models;

use App\Http\Controllers\FavoriteController;
use App\Traits\ScopeRememberCache;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Backpack\CRUD\CrudTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class Drug extends Model
{
    use SoftDeletes;
    use CrudTrait, Sluggable, ScopeRememberCache;

    /**
     * @var array
     */
    const PRESCRIPTION = ['NO' => 1, 'NORMAL' => 2, 'HIGH' => 3];

    const FAVORITES_COOKIE = 'favorites';

    const FAVORITES_EXPIRES = 43200;
    /*
   |--------------------------------------------------------------------------
   | GLOBAL VARIABLES
   |--------------------------------------------------------------------------
   */

    //protected $table = 'drugs';
    //protected $primaryKey = 'id';
    // public $timestamps = false;
    protected $guarded = [];
    protected $appends = ['image', 'url', 'is_favorite', 'title_admin'];
    // protected $fillable = [];
    // protected $hidden = [];
    // protected $dates = [];

    /**
     * Sluggable configuration
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    /**
     * Casting
     * @var array
     */
    protected $casts = [
        'images' => 'json',
        'type' => 'integer',
        'default_price' => 'float',
    ];

    public function pages()
    {
        return $this->belongsToMany(Page::class);
    }

    public function cities()
    {
        return $this->belongsToMany(City::class)->using(CityDrug::class)->as('price')->withPivot('price', 'discount', 'discount_is_percent', 'start_at', 'end_at');
    }

    public function forUses()
    {
        return $this->belongsToMany(ForUse::class);
    }

    /**
     * get drugs
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function drugstores()
    {
        return $this->belongsToMany(Drugstore::class)->using(DrugDrugstore::class)->where('in_stock', '>', 0)->withPivot('in_stock')->withTimestamps();
    }

    /**
     * get articles
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function articles()
    {
        return $this->belongsToMany(Article::class);
    }

    /**
     * get category
     * @return \Illuminate\Database\Eloquent\Relations\belongsTo
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * get vidal product
     * @return \Illuminate\Database\Eloquent\Relations\hasOne
     */
    public function vidalProduct()
    {
        return $this->hasOne(VidalProduct::class, 'RegistrationNumber', 'registration_number')->with('vidalDocuments');
    }

    /**
     * get manufacturer
     * @return \Illuminate\Database\Eloquent\Relations\belongsTo
     */
    public function manufacturer()
    {
        return $this->belongsTo(Manufacturer::class);
    }

    /**
     * Get main image src
     *
     * @return string
     */
    public function getImageAttribute()
    {
        if ($this->images) {
            return current($this->images);
        }
        return 'images/no_photo.png';
    }

    /**
     * Get main image src
     *
     * @return string
     */
    public function getUrlAttribute()
    {
        return route('catalog.view', [$this->category->slug, $this->slug], false);
    }

    /**
     * Get main image src
     *
     * @return string
     */
    public function getIsFavoriteAttribute()
    {
        $favouriteIds = unserialize(\Cookie::get(self::FAVORITES_COOKIE));
        if (!$favouriteIds) {
            return false;
        }
        return in_array($this->id, unserialize(\Cookie::get(self::FAVORITES_COOKIE)));
    }

    /**
     * Get main image src
     *
     * @return string
     */
    public function getTitleAdminAttribute()
    {
        return "ID {$this->id} {$this->title}";
    }

    /**
     * Analogs of drug
     *
     * @todo Analogs
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param Drug $drug
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeIsAnalog($query, Drug $drug)
    {
        return $query->whereNotNull('molecular_composition')->where('molecular_composition', $drug->molecular_composition);
    }

    public function getAnalogsAttribute()
    {
        return self::getAnalogs($this);
    }

    public function scopeGetAnalogs($query, Drug $drug, $cityId = null, $limit = 4)
    {
        $drugs = Drug::select('drugs.*')
            ->withPrice($cityId)
            ->exclude($drug->id)
            ->isAnalog($drug)
            ->with('manufacturer')
            ->withDrugstores($cityId)
            ->limit($limit)
            ->get();
        return $drugs;
    }
    /**
     * Scope drugs with category and descendants
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param integer $category_id
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeWithCategoryId($query, $category_id = null)
    {
        if ($category_id) {
            $categories = Category::whereDescendantOrSelf($category_id)->pluck('id');
            return $query->whereIn('category_id', $categories);
        }
        return $query;
    }

    /**
     * Hits of sales
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeIsHit($query)
    {
        return $query->where('drugs.is_hit', true);
    }

    /**
     * Scope is 24h
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeIs24h($query)
    {
        return $query->whereHas('drugstores', function($query) {
            $query->where('drugstores.is_24h', true)->rememberCache(60);
        });
    }

    /**
     * Hits of sales
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeWithCityId($query, $city_id)
    {
        return $query->with(['drugstores' => function($query) use ($city_id) {
            $query->where('drugstores.city_id', $city_id)->rememberCache(60);
        }]);
    }

    /**
     * Hits of sales
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeWithDrugstoreId($query, $drugstore_id = null)
    {
        if ($drugstore_id) {
            $query->where('drug_drugstore.drugstore_id', $drugstore_id);
        }
        return $query;
    }

    public function scopeIsTooBuy($query, Drug $drug)
    {
        return $query->where('drugs.id', '<>', $drug->id)->whereNotNull('too_buy')->where('too_buy', $drug->too_buy);
    }

    public function getIsTooBuyAttribute()
    {
        return self::getIsTooBuy($this);
    }

    public function scopeGetIsTooBuy($query, Drug $drug, $cityId = null, $limit = 4)
    {
        $drugs = Drug::select('drugs.*')
            ->withPrice($cityId)
            ->with('manufacturer')
            ->withDrugstores($cityId)
            ->exclude($drug->id)
            ->isTooBuy($drug)
            ->limit($limit)
            ->get();
        return $drugs;
    }


    public function scopeExclude($query, $id)
    {
        return $query->where('drugs.id', '<>', $id);
    }

    /**
     * Buys with drug
     *
     * @todo Buys
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param integer $cityId
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeWithPrice($query, $cityId = null)
    {
        if (is_null($cityId)) {
            $cityId = session()->get('city_id', false);
        }
        if ($cityId) {
            return $query->join('city_drug', 'drugs.id', '=', 'city_drug.drug_id')
                ->where('city_drug.city_id', $cityId)
                ->addSelect(\DB::raw('
                    city_drug.price AS price, city_drug.discount_is_percent AS discount_is_percent,CASE
                        WHEN CURDATE() BETWEEN city_drug.start_at and city_drug.end_at THEN city_drug.discount
                        ELSE NULL
                    END as discount
                '));
        }
        return $query->addSelect(\DB::raw('default_price AS price, null AS discount, false AS discount_is_percent'));
    }


    public function scopeOnlyWithDiscount($query, $cityId = null)
    {
        if (is_null($cityId)) {
            $cityId = session()->get('city_id', false);
        }
        if ($cityId) {
            return $query->join('city_drug', 'drugs.id', '=', 'city_drug.drug_id')
                ->where('city_drug.city_id', $cityId)
                ->whereRaw('CURDATE() BETWEEN city_drug.start_at and city_drug.end_at')
                ->whereNotNull('city_drug.discount')
                ->where('city_drug.discount', '>', 0)
                ->addSelect(\DB::raw('
                    city_drug.price AS price,
                    city_drug.discount_is_percent AS discount_is_percent,
                    city_drug.discount as discount
                '));
        }
        return $query->addSelect(\DB::raw('default_price AS price, null AS discount, false AS discount_is_percent'));
    }

    public function scopeWithDrugstores($query, $cityId = null, $is24h = false)
    {
        return $query
            ->join('drug_drugstore', 'drugs.id', '=', 'drug_drugstore.drug_id')
            ->join('drugstores', 'drugstores.id', '=', 'drug_drugstore.drugstore_id')
            ->when(!is_null($cityId), function ($query) use ($cityId) {
                return $query->where('drugstores.city_id', $cityId);
            })
            ->when($is24h, function ($query) {

resources/views/catalog/category.blade.php
@extends('layouts.main')

@section('content')
	<div class="grid-container">
		<div class="grid-x grid-margin-x">
			<div class="cell small-12 margin-bottom-1 margin-top-1">
				@if (!empty($category))
					{!! Breadcrumbs::render('catalog.category', $category) !!}
				@elseif ($q)
					{!! Breadcrumbs::render('catalog.search', $q) !!}
				@endif
			</div>
		</div>
		<div class="grid-x grid-margin-x catalog-category">
			<div class="cell small-12 medium-4 large-3 margin-bottom-1">
				<catalog-filter
					class="margin-bottom-1"
					:q="'{{ !empty($q) ? $q : '' }}'"
					:category="{{ isset($category) ? $category->toJson() : 0 }}"
					:city-id="{{ session()->get('city_id') }}"></catalog-filter>
				@if(!empty($category))
					{!! \App\Http\Controllers\CatalogController::sidebarCategories($category) !!}
				@endif
				@include('articles.sidebar')
			</div>
			<div class="cell small-12 medium-8 large-9">
				@if (!empty($category))
					<catalog-items
						class="margin-bottom-1"
						{{--:current-page="{{ $page }}"--}}
						:category="{{ $category->toJson() }}"
						:items="{{ $items->toJson() }}"
						:drugstores="{{ $drugstores->toJson() }}"></catalog-items>
				@elseif ($q)
					<catalog-items
						class="margin-bottom-1"
						{{--:current-page="{{ $page }}"--}}
						:q="'{{ $q }}'"
						:dosage-forms="{{ $dosageForms }}"
						:drugstores="{{ $drugstores->toJson() }}"
						:suggest="'{{ $suggest }}'"></catalog-items>
				@endif

				@include('individuals.category')
			</div>
        </div>
	</div>
	@if(!empty($category->seoTextFull))
		<div class="grid-container">
			{!! $category->seoTextFull !!}
		</div>
	@endif
@endsection

resources/views/catalog/index.blade.php
@extends('layouts.main')

@section('content')
	<div class="grid-container">
		<div class="grid-x grid-margin-x">
			<div class="cell small-12 margin-bottom-1 margin-top-1">
				{!! Breadcrumbs::render('catalog.index') !!}
			</div>
		</div>
		<catalog-categories :categories="'{{ $categories }}'"></catalog-categories>
	</div>
	@if(!empty($city->seo_text_catalog))
		<div class="grid-container">
			{!! $city->seo_text_catalog !!}
		</div>
	@endif
@endsection

resources/views/catalog/sidebar-categories.blade.php
@if ($sidebarCategories->isNotEmpty())
	<sidebar-categories :sidebar-categories="{{ $sidebarCategories->toJson() }}"></sidebar-categories>
@endif

resources/views/catalog/view.blade.php
@extends('layouts.main')

@section('content')
	<div class="grid-container">
		<div class="grid-x grid-margin-x">
			<div class="cell small-12 margin-bottom-1 margin-top-1">
				{!! Breadcrumbs::render('catalog.view', $drug) !!}
			</div>
		</div>
		<div class="grid-x grid-margin-x catalog-view">
			<div class="cell small-12 medium-6 drug margin-bottom-1 show-for-small-only">
				<h1 class="drug__title margin-bottom-1 ">
					{{ $drug->title }}
				</h1>
			</div>
			<div class="cell small-12 medium-6 margin-bottom-1 drug__images text-center">
				<div class="statuses">
				@if ($drug->type == \App\Models\Drug::PRESCRIPTION['NORMAL'])
					<div class="prescription padding-horizontal-1" title="Товар продается при наличии рецепта">
						<i class="icon-pharmacy-icon"></i> Рецептурный препарат
					</div>
				@elseif ($drug->type == \App\Models\Drug::PRESCRIPTION['HIGH'])
					<div class="super-prescription padding-horizontal-1" title="Товар продается только при наличии рецепта по форме 107-1/у">
						<i class="icon-pharmacy-icon"></i> Строгорецептурный препарат
					</div>
				@endif
				</div>
				<img src="{{ asset($drug->image) }}" title="{{ $drug->title }}" alt="{{ $drug->title }}"
					 class="drug__images__image"/>
			</div>
			<div class="cell small-12 medium-6 drug margin-bottom-1">
				<h1 class="drug__title margin-bottom-1 hide-for-small-only">
					{{ $drug->title }}
				</h1>
				@if ($drug->manufacturer->title)
				<div class="drug__manufacturer margin-bottom-1">
					Производитель: {{ $drug->manufacturer->title }}
					<favorite :drug-id="{{ $drug->id }}" :is-favorite="{{(int)$drug->is_favorite}}"></favorite>
				</div>
				@endif
				<div class="drug__in_stock margin-bottom-1">
					Есть в наличии на выбранной аптеке
				</div>
				<add-to-basket :drug="{{ $drug->toJson() }}" :current-drugstore="{{$currentDrugstore}}"></add-to-basket>
				<div class="drug__info">
					<div class="callout lightblue flex-container align-justify">
						<div class="align-self-middle margin-right-1">
							<i class="icon-receiving-time" style="font-size:1.7rem"></i>
						</div>
						<div class="align-self-middle">
							Все товары в заказе резирвируются на 24 часа, после этого заказ автоматически отменяется
						</div>
					</div>
				</div>
			</div>
			@if ($drug->text)
				<div class="drug__description margin-bottom-1">
					{!! htmlspecialchars_decode($drug->text) !!}
				</div>
			@endif
        </div>
        @if (!$drug->analogs->isEmpty())
            <drugs-hits :drugs="{{ $drug->analogs->toJson() }}" :title="'Аналоги'"></drugs-hits>
        @endif
        @if ($recommendedDrugs->isNotEmpty())
			<div class="grid-x grid-margin-x">
				<div class="cell small-12 margin-bottom-1">
					<individuals :drugs="{{ $recommendedDrugs->toJson() }}"
						:limit="4"
						:css-class="'blue'"
						:title="'Вас может заинтересовать'">
					</individuals>
				</div>
			</div>
        @endif
	</div>

	@if(!empty($drug->seo_text))
		<div class="grid-container">
			{!! $drug->seo_text !!}
		</div>
	@endif
@endsection